- job:
    name: zuul-preview-build
    parent: openstack-buildset-registry
    run: playbooks/build-image.yaml
    vars:
      docker_images:
        - context: .
          repository: zuul/zuul-preview

- project:
    check:
      jobs:
        - zuul-preview-build
    gate:
      jobs:
        - zuul-preview-build
