[package]
name = "zuul-preview"
version = "0.1.0"
authors = ["Clint Byrum <clint@fewbar.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
lru = "*"
serde = { version = "1.0", features = ["derive"] }
custom_error = "*"
